# Generated by Django 4.2.3 on 2023-07-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('chat_id', models.CharField(max_length=56, primary_key=True, serialize=False, unique=True, verbose_name='Telegram chat id')),
                ('privat_url', models.CharField(default='none', max_length=56, verbose_name='Приватная ссылка пользователя')),
                ('public_url', models.CharField(default='none', max_length=56, verbose_name='Публичная ссылка пользователя')),
                ('last_callback', models.CharField(default='none', max_length=56, verbose_name='Последний callback')),
                ('last_id', models.CharField(default='none', max_length=56, verbose_name='Последний callback ID')),
                ('qr_id', models.CharField(default='none', max_length=256, verbose_name='ID qr для телеграмма')),
            ],
            options={
                'verbose_name': 'Пользователь TG',
                'verbose_name_plural': 'Пользователи TG',
            },
        ),
        migrations.CreateModel(
            name='Routers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256, verbose_name='Id пользователя')),
                ('public_url', models.CharField(default='none', max_length=256, verbose_name='публичная ссылка')),
                ('privat_url', models.CharField(max_length=256, verbose_name='пользовательская ссылка')),
            ],
            options={
                'verbose_name': 'Роут',
                'verbose_name_plural': 'Роуты',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=56, verbose_name='Логин пользователя')),
                ('user_pass', models.CharField(max_length=56, verbose_name='Пароль пользователя')),
                ('user_mail', models.CharField(max_length=56, verbose_name='Почта пользователя')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
