# Generated by Django 4.2.2 on 2023-06-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=56, verbose_name='Логин пользователя')),
                ('pas', models.TextField(verbose_name='Пароль пользователя')),
                ('mail', models.CharField(max_length=56, verbose_name='Почтовый адрес пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
