# Generated by Django 4.2.2 on 2023-06-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=56, verbose_name='Логин пользователя')),
                ('user_pass', models.CharField(max_length=56, verbose_name='Пароль пользователя')),
                ('user_mail', models.CharField(max_length=56, verbose_name='Почта пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
