# Generated by Django 4.2.2 on 2023-06-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mail',
            field=models.CharField(max_length=56, verbose_name='Почта пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='pas',
            field=models.CharField(max_length=56, verbose_name='Пароль пользователя'),
        ),
    ]
