# Generated by Django 4.2.2 on 2023-06-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_users_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256, verbose_name='Id пользователя')),
                ('public_url', models.CharField(max_length=256, verbose_name='публичная ссылка')),
                ('privat_url', models.CharField(max_length=256, verbose_name='пользовательская ссылка')),
            ],
            options={
                'verbose_name': 'Роут',
                'verbose_name_plural': 'Роуты',
            },
        ),
    ]
