# Generated by Django 4.2.2 on 2023-06-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_routers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routers',
            name='public_url',
            field=models.CharField(default='none', max_length=256, verbose_name='публичная ссылка'),
        ),
    ]
