name: remote ssh command
on:
  release:
    types: [created, published]
  workflow_dispatch:
    inputs:
      comment:
        description: "Comments"
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Run commands on server
      uses: appleboy/ssh-action@master
      with:
        host: 45.131.41.34 
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          whoami
          ls -al
          
